In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("winemag-data-130k-v2.csv", index)

In [32]:
data.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

# Filtrando y agrupando datos

## Metodo simple

Podemos filtrar la base de datos en base a condiciones sobre una o mas de sus columnas. Para esto usamos la siguiente sintaxis: 

```data[condicion que queremos que se cumpla]```

Las condiciones se veran de la siguiente forma

* ```data[columna] == valor```
* ```data[columna] > valor```
* ```data[columna] =! valor```
* ```data[columna].isin(lista de valores)```

In [14]:
# Vinos de Estados Unidos

data[data["country"] == 'US']

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
10,10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
12,12,US,"Slightly reduced, this wine offers a chalky, t...",NaN,87,34.0,California,Alexander Valley,Sonoma,Virginie Boone,@vboone,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,Cabernet Sauvignon,Louis M. Martini
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129945,129945,US,Hailing from one of the more popular vineyards...,Jurassic Park Vineyard Old Vines,90,20.0,California,Santa Ynez Valley,Central Coast,Matt Kettmann,@mattkettmann,Birichino 2013 Jurassic Park Vineyard Old Vine...,Chenin Blanc,Birichino
129949,129949,US,There's no bones about the use of oak in this ...,Barrel Fermented,90,35.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Flora Springs 2013 Barrel Fermented Chardonnay...,Chardonnay,Flora Springs
129950,129950,US,This opens with herbaceous dollops of thyme an...,Blocks 7 & 22,90,35.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Hendry 2012 Blocks 7 & 22 Zinfandel (Napa Valley),Zinfandel,Hendry
129952,129952,US,This Zinfandel from the eastern section of Nap...,NaN,90,22.0,California,Chiles Valley,Napa,Virginie Boone,@vboone,Houdini 2011 Zinfandel (Chiles Valley),Zinfandel,Houdini
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation

In [15]:
# Vinos que valen mas de 50 dolares

data[data["price"] > 50]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
25,25,US,Oak and earth intermingle around robust aromas...,King Ridge Vineyard,87,69.0,California,Sonoma Coast,Sonoma,Virginie Boone,@vboone,Castello di Amorosa 2011 King Ridge Vineyard P...,Pinot Noir,Castello di Amorosa
59,59,US,"Aromas of cranberry, barrel spice and herb are...",NaN,86,55.0,Washington,Columbia Valley (WA),Columbia Valley,Sean P. Sullivan,@wawinereport,Mellisoni 2014 Malbec (Columbia Valley (WA)),Malbec,Mellisoni
60,60,US,"Syrupy and dense, this wine is jammy in plum a...",Estate,86,100.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Okapi 2013 Estate Cabernet Sauvignon (Napa Val...,Cabernet Sauvignon,Okapi
63,63,France,"This fat, yeasty Champagne is comprised predom...",Brut Rosé,86,58.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Roland Champion NV Brut Rosé (Champagne),Champagne Blend,Roland Champion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129934,129934,Austria,"You can feel the unctuous, oily richness as so...",Alte Reben,91,54.0,Kamptal,NaN,NaN,Roger Voss,@vossroger,Bründlmayer 2007 Alte Reben Grüner Veltliner (...,Grüner Veltliner,Bründlmayer
129936,129936,France,A blend from several premier cru vineyards in ...,Premier Cru,91,66.0,Burgundy,Pommard,NaN,Roger Voss,@vossroger,Bouchard Père & Fils 2005 Premier Cru (Pommard),Pinot Noir,Bouchard Père & Fils
129939,129939,Austria,"A true TBA, its very rich, toffee-flavored, in...",Grand Vin,91,70.0,Burgenland,NaN,NaN,Roger Voss,@vossroger,Schloss Halbturn 2004 Grand Vin White (Burgenl...,White Blend,Schloss Halbturn
129959,129959,France,The granite soil of the Brand Grand Cru vineya...,Brand Grand Cru,90,57.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Cave de Turckheim 2010 Brand Grand Cru Pinot G...,Pinot Gris,Cave de Turckheim
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation

In [16]:
# Vinos de Chile y Argentina

data[data["country"].isin(["Chile", "Argentina"])]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
16,16,Argentina,"Baked plum, molasses, balsamic vinegar and che...",Felix,87,30.0,Other,Cafayate,NaN,Michael Schachner,@wineschach,Felix Lavaque 2010 Felix Malbec (Cafayate),Malbec,Felix Lavaque
17,17,Argentina,Raw black-cherry aromas are direct and simple ...,Winemaker Selection,87,13.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Gaucho Andino 2011 Winemaker Selection Malbec ...,Malbec,Gaucho Andino
36,36,Chile,"White flower, lychee and apple aromas carry th...",Estate,86,15.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Estampa 2011 Estate Viognier-Chardonnay (Colch...,Viognier-Chardonnay,Estampa
44,44,Chile,A berry aroma comes with cola and herb notes. ...,NaN,86,9.0,Maule Valley,NaN,NaN,Michael Schachner,@wineschach,Sundance 2011 Merlot (Maule Valley),Merlot,Sundance
51,51,Chile,This is much different than Casa Silva's 2009 ...,Gran Reserva,85,22.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Casa Silva 2008 Gran Reserva Petit Verdot (Col...,Petit Verdot,Casa Silva
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129921,129921,Argentina,There is a select group of under-$20 Malbecs f...,La Madras Vineyard,91,18.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Ricardo Santos 2006 La Madras Vineyard Malbec ...,Malbec,Ricardo Santos
129925,129925,Argentina,"A lively, well-made blend of Tempranillo, Malb...",B Crux,91,24.0,Mendoza Province,Uco Valley,NaN,Michael Schachner,@wineschach,O. Fournier 2005 B Crux Red (Uco Valley),Red Blend,O. Fournier
129932,129932,Argentina,Andeluna's top wines tend to be ripe and plump...,Pasionado,91,55.0,Mendoza Province,Uco Valley,NaN,Michael Schachner,@wineschach,Andeluna 2004 Pasionado Red (Uco Valley),Red Blend,Andeluna
129938,129938,Argentina,Compared to the regular 2006 Malbec from Chaka...,Reserve,91,25.0,Mendoza Province,Luján de Cuyo,NaN,Michael Schachner,@wineschach,Chakana 2006 Reserve Malbec (Luján de Cuyo),Malbec,Chakana
129948,129948,Argentina,Raspberry and cassis aromas are fresh and upri...,Pedernal,90,43.0,Other,San Juan,NaN,Michael Schachner,@wineschach,Finca Las Moras 2010 Pedernal Malbec (San Juan),Malbec,Finca Las Moras

## Metodo query de pandas

Otra manera de filtrar los datos es usando el metodo query de pandas 

* Documentacion: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html
* Buen post con ejemplos: https://towardsdatascience.com/10-examples-that-will-make-you-use-pandas-query-function-more-often-a8fb3e9361cb

En este caso las condiciones se escriben como un gran string y se pueden mezclar facilmente entre ellas

In [34]:
data.query('country == "Chile" and points > 85')

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
36,36,Chile,"White flower, lychee and apple aromas carry th...",Estate,86,15.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Estampa 2011 Estate Viognier-Chardonnay (Colch...,Viognier-Chardonnay,Estampa
44,44,Chile,A berry aroma comes with cola and herb notes. ...,NaN,86,9.0,Maule Valley,NaN,NaN,Michael Schachner,@wineschach,Sundance 2011 Merlot (Maule Valley),Merlot,Sundance
80,80,Chile,Caramelized oak and vanilla aromas are front a...,Special Release Reserva,86,12.0,Rapel Valley,NaN,NaN,Michael Schachner,@wineschach,Aresti 2014 Special Release Reserva Carmenère ...,Carmenère,Aresti
103,103,Chile,A bright nose with green apple and citric arom...,Single Vineyard Falaris Hill,87,18.0,Leyda Valley,NaN,NaN,Michael Schachner,@wineschach,Leyda 2015 Single Vineyard Falaris Hill Chardo...,Chardonnay,Leyda
164,164,Chile,"This blend of Cabernet Sauvignon, Syrah and Me...",Condesa Real Premium Blend,91,29.0,Aconcagua Valley,NaN,NaN,Michael Schachner,@wineschach,Conde de Velázquez 2012 Condesa Real Premium B...,Red Blend,Conde de Velázquez
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129450,129450,Chile,"Spicy plum, berry and herbal aromas cover the ...",Reserva,87,11.0,Colchagua Costa,NaN,NaN,Michael Schachner,@wineschach,Oveja Negra 2014 Reserva Cabernet Sauvignon-Sy...,Cabernet Sauvignon-Syrah,Oveja Negra
129458,129458,Chile,"A ruby color and gamy, roasted aromas of plum ...",Reserva,87,13.0,San Antonio,NaN,NaN,Michael Schachner,@wineschach,Apaltagua 2015 Reserva Pinot Noir (San Antonio),Pinot Noir,Apaltagua
129640,129640,Chile,The 2012 vintage was so hot in Chile that harv...,Terrunyo Costa Los Boldos Vineyard Block 5,90,30.0,Casablanca Valley,NaN,NaN,Michael Schachner,@wineschach,Concha y Toro 2012 Terrunyo Costa Los Boldos V...,Sauvignon Blanc,Concha y Toro
129812,129812,Chile,"Opens with a light, herbal bouquet that featur...",Anke Blend 3,89,18.0,Maipo Valley,NaN,NaN,Michael Schachner,@wineschach,Santa Alicia 2007 Anke Blend 3 Red (Maipo Valley),Red Blend,Santa Alicia
129830,129830,Chile,After several years spent in Chile's land of t...,Reserva,86,10.0,Rapel Valley,NaN,NaN,Michael Schachner,@wineschach,Santa Carolina 2008 Reserva Sauvignon Blanc (R...,Sauvignon Blanc,Santa Carolina

## Agrupando datos

Para sacar metricas por datos agrupados podemos usar el group by. Podemos aplicar operaciones de: 

* suma
* media
* conteo

In [31]:
data.groupby(['country'])["price"].mean()

country
Argentina                 24.510117
Armenia                   14.500000
Australia                 35.437663
Austria                   30.762772
Bosnia and Herzegovina    12.500000
Brazil                    23.765957
Bulgaria                  14.645390
Canada                    35.712598
Chile                     20.786458
China                     18.000000
Croatia                   25.450704
Cyprus                    16.272727
Czech Republic            24.250000
Egypt                           NaN
England                   51.681159
France                    41.139120
Georgia                   19.321429
Germany                   42.257547
Greece                    22.364425
Hungary                   40.648276
India                     13.333333
Israel                    31.768916
Italy                     39.663770
Lebanon                   30.685714
Luxembourg                23.333333
Macedonia                 15.583333
Mexico                    26.785714
Moldova                   16.745763
Morocco                   19.500000
New Zealand               26.931785
Peru                      18.062500
Portugal                  26.218256
Romania                   15.241667
Serbia                    24.500000
Slovakia                  16.000000
Slovenia                  24.812500
South Africa              24.668987
Spain                     28.215275
Switzerland               85.285714
Turkey                    24.633333
US                        36.573464
Ukraine                    9.214286
Uruguay                   26.403670
Name: price, dtype: float64

In [25]:
data.groupby(['country']).count()

,Unnamed: 0,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,,
Argentina,3800,3800,2902,3800,3756,3800,3747,0,3797,3797,3800,3800,3800
Armenia,2,2,2,2,2,2,0,0,2,2,2,2,2
Australia,2329,2329,1640,2329,2294,2329,2327,0,2037,2037,2329,2329,2329
Austria,3345,3345,2825,3345,2799,3345,0,0,3337,3337,3345,3345,3345
Bosnia and Herzegovina,2,2,1,2,2,2,0,0,2,1,2,2,2
Brazil,52,52,51,52,47,52,0,0,52,52,52,52,52
Bulgaria,141,141,93,141,141,141,0,0,141,122,141,141,141
Canada,257,257,179,257,254,257,257,0,256,241,257,257,257
Chile,4472,4472,3879,4472,4416,4472,0,0,4361,4361,4472,4471,4472
China,1,1,1,1,1,1,0,0,1,1,1,1,1
Croatia,73,73,48,73,71,73,0,0,73,34,73,73,73
Cyprus,11,11,9,11,11,11,0,0,11,11,11,11,11
Czech Republic,12,12,7,12,12,12,0,0,12,8,12,12,12
Egypt,1,1,1,1,0,1,0,0,1,1,1,1,1
England,74,74,74,74,69,74,0,0,74,74,74,74,74
France,22093,22093,14530,22093,17776,22093,22017,0,21828,21828,22093,22093,22093
Georgia,86,86,62,86,84,86,0,0,86,64,86,86,86
Germany,2165,2165,2006,2165,2120,2165,0,0,2134,375,2165,2165,2165
Greece,466,466,319,466,461,466,0,0,466,466,466,466,466
Hungary,146,146,124,146,145,146,0,0,145,113,146,146,146
India,9,9,4,9,9,9,0,0,9,9,9,9,9
Israel,505,505,435,505,489,505,0,0,500,500,505,505,505
Italy,19540,19540,13889,19540,16914,19540,19513,0,11042,11042,19540,19540,19540
Lebanon,35,35,30,35,35,35,0,0,35,25,35,35,35
Luxembourg,6,6,6,6,6,6,0,0,6,6,6,6,6
Macedonia,12,12,5,12,12,12,0,0,12,11,12,12,12
Mexico,70,70,53,70,70,70,0,0,65,65,70,70,70
Moldova,59,59,52,59,59,59,0,0,59,58,59,59,59
Morocco,28,28,16,28,28,28,0,0,28,26,28,28,28
New Zealand,1419,1419,684,1419,1378,1419,0,0,1311,1311,1419,1419,1419
Peru,16,16,16,16,16,16,0,0,16,16,16,16,16
Portugal,5691,5691,5105,5691,4875,5691,0,0,5686,5686,5691,5691,5691
Romania,120,120,114,120,120,120,0,0,120,79,120,120,120
Serbia,12,12,9,12,12,12,0,0,12,12,12,12,12
Slovakia,1,1,0,1,1,1,0,0,1,0,1,1,1
Slovenia,87,87,60,87,80,87,0,0,87,61,87,87,87
South Africa,1401,1401,822,1401,1293,1401,0,0,1328,1328,1401,1401,1401
Spain,6645,6645,5320,6645,6573,6645,6637,0,6581,6581,6645,6645,6645
Switzerland,7,7,3,7,7,7,0,0,7,7,7,7,7
Turkey,90,90,63,90,90,90,0,0,90,85,90,90,90
US,54504,54504,36908,54504,54265,54504,54226,50511,37730,34741,54504,54504,54504
Ukraine,14,14,12,14,14,14,0,0,14,12,14,14,14
Uruguay,109,109,95,109,109,109,0,0,109,109,109,109,109

# 1. Metricas generales

In [4]:
data.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [3]:
data.describe()

          Unnamed: 0         points          price
count  129971.000000  129971.000000  120975.000000
mean    64985.000000      88.447138      35.363389
std     37519.540256       3.039730      41.022218
min         0.000000      80.000000       4.000000
25%     32492.500000      86.000000      17.000000
50%     64985.000000      88.000000      25.000000
75%     97477.500000      91.000000      42.000000
max    129970.000000     100.000000    3300.000000

# 2. Puntajes de vinos de Francia

# 3. Precios de vinos de designacion Reserva

# 4. Tipos de vinos evaluados que se producen en California

# 5. Vinos de Chile evaluados con mas de 90 puntos

# 6. Promedio de puntaje de vino por pais

# 7. Promedio de puntaje dado por tester

# 8. Puntajes por pais de vinos Pinot Noir