In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("winemag-data-130k-v2.csv")

In [3]:
data.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

# Filtrando y agrupando datos

## Filtrar: metodo simple

Podemos filtrar la base de datos en base a condiciones sobre una o mas de sus columnas. Para esto usamos la siguiente sintaxis: 

```data[condicion que queremos que se cumpla]```

Las condiciones se veran de la siguiente forma

* ```data[columna] == valor```
* ```data[columna] > valor```
* ```data[columna] =! valor```
* ```data[columna].isin(lista de valores)```

In [7]:
data["country"].unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

In [6]:
# Vinos de Estados Unidos

# asignamos la tabla filtrada al nombre vinos_us
vinos_us = data[data["country"] == 'US']

# vemos los valores distintos de la columna pais
print(vinos_us["country"].unique())

['US']

In [11]:
vinos_us.describe(include="all")

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
count,54504.000000,54504,54504,36908,54504.00000,54265.000000,54504,54226,50511,37730,34741,54504,54504,54504
unique,NaN,1,50449,14183,NaN,NaN,27,264,17,15,12,50229,257,5375
top,NaN,US,"Seductively tart in lemon pith, cranberry and ...",Reserve,NaN,NaN,California,Napa Valley,Central Coast,Virginie Boone,@vboone,Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...,Pinot Noir,Testarossa
freq,NaN,54504,3,1485,NaN,NaN,36247,4480,11065,9537,9537,11,9885,218
mean,65467.828563,NaN,NaN,NaN,88.56372,36.573464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,37572.539161,NaN,NaN,NaN,3.11484,27.088857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.000000,NaN,NaN,NaN,80.00000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,33067.750000,NaN,NaN,NaN,86.00000,20.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,65678.500000,NaN,NaN,NaN,88.00000,30.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,98191.250000,NaN,NaN,NaN,91.00000,45.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,129967.000000,NaN,NaN,NaN,100.00000,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Vinos que valen mas de 50 dolares

vinos_50mas = data[data["price"] > 50]

In [14]:
vinos_50mas.describe()

          Unnamed: 0        points         price
count   19774.000000  19774.000000  19774.000000
mean    65621.033276     91.347881     88.728836
std     37533.147331      2.669774     78.943042
min         4.000000     80.000000     51.000000
25%     33821.500000     90.000000     60.000000
50%     65483.500000     92.000000     70.000000
75%     98140.750000     93.000000     90.000000
max    129967.000000    100.000000   3300.000000

In [23]:
# Vinos de Chile y Argentina

vinos_CAI = data[data["country"].isin(["Chile", "Argentina", "Italy"])]
vinos_CAI["country"].unique()

array(['Italy', 'Argentina', 'Chile'], dtype=object)

## Metodo query de pandas

Otra manera de filtrar los datos es usando el metodo query de pandas 

* Documentacion: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html
* Buen post con ejemplos: https://towardsdatascience.com/10-examples-that-will-make-you-use-pandas-query-function-more-often-a8fb3e9361cb

En este caso las condiciones se escriben como un gran string y se pueden mezclar facilmente entre ellas

In [25]:
vinos_buenos_chile = data.query('country == "Chile" and points > 85')

In [26]:
vinos_buenos_chile.describe(include="all")

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
count,2858.000000,2858,2858,2595,2858.000000,2821.000000,2858,0,0,2796,2796,2858,2857,2858
unique,NaN,1,2636,827,NaN,NaN,43,0,0,3,3,2632,53,241
top,NaN,Chile,"On first take, this small-batch blend of País ...",Reserva,NaN,NaN,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Garces Silva 2016 Boya Rosé (Leyda Valley),Cabernet Sauvignon,Concha y Toro
freq,NaN,2858,2,264,NaN,NaN,594,NaN,NaN,2785,2785,2,529,130
mean,64277.611267,NaN,NaN,NaN,88.063331,24.976604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,37991.714955,NaN,NaN,NaN,1.872702,26.081178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,36.000000,NaN,NaN,NaN,86.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,30259.000000,NaN,NaN,NaN,87.000000,13.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,65432.500000,NaN,NaN,NaN,88.000000,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,98218.000000,NaN,NaN,NaN,89.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,129830.000000,NaN,NaN,NaN,95.000000,400.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Agrupando datos

Para sacar metricas por datos agrupados podemos usar el group by. Podemos aplicar operaciones de: 

* suma
* media
* conteo

In [27]:
# Calcular el precio promedio de vinos por pais

data.groupby(['country'])["price"].mean()

country
Argentina                 24.510117
Armenia                   14.500000
Australia                 35.437663
Austria                   30.762772
Bosnia and Herzegovina    12.500000
Brazil                    23.765957
Bulgaria                  14.645390
Canada                    35.712598
Chile                     20.786458
China                     18.000000
Croatia                   25.450704
Cyprus                    16.272727
Czech Republic            24.250000
Egypt                           NaN
England                   51.681159
France                    41.139120
Georgia                   19.321429
Germany                   42.257547
Greece                    22.364425
Hungary                   40.648276
India                     13.333333
Israel                    31.768916
Italy                     39.663770
Lebanon                   30.685714
Luxembourg                23.333333
Macedonia                 15.583333
Mexico                    26.785714
Moldova                   16.745763
Morocco                   19.500000
New Zealand               26.931785
Peru                      18.062500
Portugal                  26.218256
Romania                   15.241667
Serbia                    24.500000
Slovakia                  16.000000
Slovenia                  24.812500
South Africa              24.668987
Spain                     28.215275
Switzerland               85.285714
Turkey                    24.633333
US                        36.573464
Ukraine                    9.214286
Uruguay                   26.403670
Name: price, dtype: float64

Podemos hacer lo mismo que hace el group by con otros metodos, pero usar group by nos facilita la vida

In [28]:
# Alternativa 1: hacer esto para cada pais

data[data["country"]== "Chile"]["price"].mean()

20.786458333333332

In [30]:
# Alternativa 2: hacer lo de arriba con un for

paises = list(data["country"].unique())

In [32]:
for pais in paises:
    print(pais, data[data["country"]==pais]["price"].mean())

Italy 39.663769658271256
Portugal 26.21825641025641
US 36.5734635584631
Spain 28.215274608245853
France 41.139120162016205
Germany 42.25754716981132
Argentina 24.510117145899894
Chile 20.786458333333332
Australia 35.43766346992153
Austria 30.76277241872097
South Africa 24.668986852281517
New Zealand 26.93178519593614
Israel 31.768916155419223
Hungary 40.648275862068964
Greece 22.364425162689805
Romania 15.241666666666667
Mexico 26.785714285714285
Canada 35.71259842519685
nan nan
Turkey 24.633333333333333
Czech Republic 24.25
Slovenia 24.8125
Luxembourg 23.333333333333332
Croatia 25.450704225352112
Georgia 19.321428571428573
Uruguay 26.40366972477064
England 51.68115942028985
Lebanon 30.685714285714287
Serbia 24.5
Brazil 23.76595744680851
Moldova 16.74576271186441
Morocco 19.5
Peru 18.0625
India 13.333333333333334
Bulgaria 14.645390070921986
Cyprus 16.272727272727273
Armenia 14.5
Switzerland 85.28571428571429
Bosnia and Herzegovina 12.5
Ukraine 9.214285714285714
Slovakia 16.0
Macedonia 15.583333333333334
China 18.0
Egypt nan

# 1. Metricas generales

In [33]:
data.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [34]:
data.describe(include="all")

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
count,129971.000000,129908,129971,92506,129971.000000,120975.000000,129908,108724,50511,103727,98758,129971,129970,129971
unique,NaN,43,119955,37979,NaN,NaN,425,1229,17,19,15,118840,707,16757
top,NaN,US,"Stalky aromas suggest hay and green herbs, wit...",Reserve,NaN,NaN,California,Napa Valley,Central Coast,Roger Voss,@vossroger,Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...,Pinot Noir,Wines & Winemakers
freq,NaN,54504,3,2009,NaN,NaN,36247,4480,11065,25514,25514,11,13272,222
mean,64985.000000,NaN,NaN,NaN,88.447138,35.363389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,37519.540256,NaN,NaN,NaN,3.039730,41.022218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,80.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,32492.500000,NaN,NaN,NaN,86.000000,17.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,64985.000000,NaN,NaN,NaN,88.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,97477.500000,NaN,NaN,NaN,91.000000,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,129970.000000,NaN,NaN,NaN,100.000000,3300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 2. Distribucion de puntajes de vinos de Francia

In [36]:
# Usando filtros simple, primero obtenemos los vinos de Francia

vinos_france = data[data["country"] == "France"]

In [37]:
vinos_france.describe()

          Unnamed: 0        points         price
count   22093.000000  22093.000000  17776.000000
mean    64804.002987     88.845109     41.139120
std     37315.795085      3.044423     73.769404
min         7.000000     80.000000      5.000000
25%     32574.000000     87.000000     16.000000
50%     64509.000000     89.000000     25.000000
75%     97108.000000     91.000000     43.000000
max    129970.000000    100.000000   3300.000000

Vemos que el promedio de puntos de los vinos de Francia es 88, con un minimo de 80 puntos y un maximo de 100.

# 3. Precios de vinos de designacion Reserva

In [40]:
data["designation"].value_counts()

Reserve                          2009
Estate                           1322
Reserva                          1259
Riserva                           698
Estate Grown                      621
                                 ...
Heritage Selection Estate           1
Ambrosia Riserva                    1
Tendresse Grand Cru Sec             1
Forster Mariengarten Kabinett       1
La Perrière                         1
Name: designation, Length: 37979, dtype: int64

In [64]:
reserva = ["Reserve", "Reserva", "Riserva"]

vinos_reserva = data[data["designation"].isin(reserva)]

In [65]:
vinos_reserva["price"].describe()

count    3806.000000
mean       35.556752
std        38.470779
min         5.000000
25%        15.000000
50%        25.000000
75%        42.000000
max       900.000000
Name: price, dtype: float64

# 4. Tipos de vinos evaluados con mas de 90 puntos que se producen en California

In [66]:
print(data["province"].unique())

['Sicily & Sardinia' 'Douro' 'Oregon' 'Michigan' 'Northern Spain' 'Alsace'
 'Rheinhessen' 'California' 'Mosel' 'Other' 'Mendoza Province' 'Virginia'
 'Beaujolais' 'Colchagua Valley' 'Southern Italy' 'Maule Valley'
 'Bordeaux' 'Maipo Valley' 'Washington' 'Central Italy' 'Champagne'
 'Burgundy' 'South Australia' 'Tejo' 'Rapel Valley' 'Galicia'
 'France Other' 'Tuscany' 'Burgenland' 'New York' 'Leyda Valley'
 'Piedmont' 'Stellenbosch' 'Simonsberg-Stellenbosch' 'Walker Bay'
 'Alentejano' 'Central Spain' 'Southwest France' 'Aconcagua Valley'
 'Loncomilla Valley' 'Marlborough' 'Northeastern Italy'
 'Casablanca Valley' 'Veneto' 'Western Cape' 'Judean Hills' 'Alentejo'
 'Coastal Region' 'Rhône Valley' 'Galilee' 'Beira Atlantico' 'Tokaj'
 'Leithaberg' 'Santorini' 'Kremstal' 'Catalonia' 'Recas' "Hawke's Bay"
 'Curicó Valley' 'Limarí Valley' 'Colchagua Costa' 'Languedoc-Roussillon'
 'Provence' 'Victoria' 'Rheingau' 'Tokaji' 'Naoussa' 'Valle de Guadalupe'
 'Central Valley' 'Lontué Valley' 'Italy Other' 'Weinviertel'
 'Thermenregion' 'Niederösterreich' 'Wagram' 'Loire Valley' 'Lombardy'
 'Ontario' 'Österreichischer Sekt' 'Kamptal' 'Steiermark' 'Südsteiermark'
 'Crete' 'Vinho Verde' 'Idaho' 'Western Australia' 'Levante'
 'Martinborough' 'Central Otago' 'Lisboa' 'Texas' 'Península de Setúbal'
 'Australia Other' 'Tasmania' 'Franken' 'Ahr' 'Nahe' nan 'Dealu Mare'
 'Port' 'Darling' 'Chile' 'Südoststeiermark' 'Corinth' 'Halkidiki'
 'Thrace' 'Pfalz' 'Robertson' 'Dan' 'Northwestern Italy' 'Andalucia'
 'Awatere Valley' 'Wiener Gemischter Satz' 'Wachau' 'Pennsylvania'
 'Swartland' 'Dão' 'Wagram-Donauland' 'Rio Claro' 'Villány'
 'Cachapoal Valley' 'Jidvei' 'America' 'Traisental' 'Bairrada'
 'Negev Hills' 'Ribatejano' 'Duriense' 'New Jersey' 'Beiras'
 'Spanish Islands' 'Upper Galilee' 'Vinho Espumante' 'Epanomi' 'Nemea'
 'Peloponnese' 'Aconcagua Costa' 'Moravia' 'Slovenia' 'Terras do Dão'
 'Beira Interior' 'Panciu' 'Bío Bío Valley' 'Romania'
 'Portuguese Table Wine' 'Minho' 'Missouri' 'New Mexico' 'Nevada'
 'Bucelas' 'Peumo' 'San Antonio' 'Carnuntum' 'Estremadura' 'Canterbury'
 'Spain Other' 'Drama' 'Ella Valley' 'Moselle Luxembourgeoise'
 'Württemberg' 'Baden' 'Pangeon' 'Elqui Valley' 'Wairau Valley' 'Istria'
 'Peljesac' 'Kakheti' 'Canelones' 'England' 'Marchigue' 'Paarl'
 'Durbanville' 'Weinland Österreich' 'Mantinia' 'Chalkidiki' 'Lebanon'
 'Setubal' 'Mosel-Saar-Ruwer' 'Colorado' 'Pocerina' 'British Columbia'
 'Puente Alto' 'Kumeu' 'Trás-os-Montes' 'Shomron' 'Rapsani' 'Vienna'
 'New South Wales' 'Nelson' 'Waipara Valley' 'Constantia' 'Arizona'
 'Pinto Bandeira' 'Primorska' 'Moldova' 'Uruguay' 'Zenata' 'South Africa'
 'Massachusetts' 'Ohio' 'Ica' 'San Vicente' 'Nashik' 'Franschhoek'
 'South Island' 'Atlantida' 'Thracian Valley' 'Tarnave' 'Vipavska Dolina'
 'Bekaa Valley' 'Elgin' 'Itata Valley' 'Table wine' 'Samson' 'Madeira'
 'Cyprus' 'Pageon' 'Vinho Espumante de Qualidade' 'Wellington'
 'Danube River Plains' 'Gisborne' 'Obidos' 'Wairarapa' 'Armenia'
 'Santa Cruz' 'Korčula' 'Viile Timisului' 'Illinois' 'Aegean'
 'Simonsberg-Paarl' 'Juanico' 'Black Sea Coastal' 'Santa Catarina'
 'Overberg' 'Atalanti Valley' 'Sebes' 'Moscatel de Setúbal' 'Macedonia'
 'Ribatejo' 'Germany' 'Palmela' 'Galil' 'Kras' 'Croatia' 'Waipara'
 'Olifants River' 'Montevideo' 'Campanha' 'Israel' 'Neusiedlersee'
 'Hungary' 'Lolol Valley' 'Cauquenes Valley' 'Groenekloof' 'Alenquer'
 'Goriska Brda' 'Murfatlar' 'Moscatel do Douro' 'Washington-Oregon'
 'New Zealand' 'Serra Gaúcha' 'San Jose' 'Vale dos Vinhedos'
 'Mittelburgenland' 'Lutzville Valley' 'North Carolina' 'Apalta' 'Malleco'
 'Guerrouane' 'Valais' 'Choapa Valley' 'Georgia' 'Ankara' 'Samos'
 'Mittelrhein' 'Eisenberg' 'Sagrada Familia' 'Austria' 'Mostar' 'Iowa'
 'Tulbagh' 'Cederberg' 'Hemel en Aarde' 'Ceres Plateau' 'Bot River'
 'Patras' 'Korinthia' 'Greece' 'San Clemente' 'Podunavlje' 'Florina'
 'Buin' 'Haut-Judeé' 'Ukraine' 'Terras do Sado'
 'Maipo Valley-Colchagua Valley' 'Brazil' 'Breedekloof'
 'Leyda Valley-Maipo Valley' 'Vermont' 'Switzerland' 'Waitaki Valley'
 'Eger' 'Golan Heights' 'Fruška Gora' 'Philadelphia' 'Muzla' 'Mátra'
 'Pirque' 'Negev' 'Pitsilia Mountains' 'East Coast'
 'Mavrodaphne of Patras' 'Attica' 'Progreso' 'Elazığ-Diyarbakir'
 'Jonkershoek Valley' 'Tikves' 'Vale Trentino' 'Turkey' 'Waiheke Island'
 'Molina' 'Serra do Sudeste' 'Dalmatian Coast' 'Eilandia'
 'Dealurile Munteniei' 'Thraki' 'Curicó and Maipo Valleys' 'Štajerska'
 'Middle and South Dalmatia' 'Kentucky' 'Župa' 'Pafos' 'Monemvasia'
 'Szekszárd' 'Elazığ' 'Cappadocia' 'Kutjevo' 'Ismarikos' 'Connecticut'
 'Sithonia' 'Curicó and Leyda Valleys' 'Agioritikos'
 'Casablanca-Curicó Valley' 'Piekenierskloof' 'Elim' 'Malgas' 'Beotia'
 'Algarve' 'Retsina' 'Amindeo' 'Coelemu' 'Cape South Coast' 'Sopron'
 'Bulgaria' 'North Dalmatia' 'Northern Cape' 'Vinho da Mesa' 'Hvar'
 'Cephalonia' 'Lemesos' 'Cahul' 'Cyclades' 'Breede River Valley' 'Ticino'
 'Vlootenburg' 'Brda' 'Dingač' 'Morocco' 'Achaia' 'Polkadraai Hills'
 'Rhode Island' 'Amyndeon' 'Vânju Mare' 'Hrvatsko Primorje'
 'Central Greece' 'Dolenjska' 'Österreichischer Perlwein' 'Requinoa'
 'Mavrodaphne de Cephalonie' 'Goumenissa' 'Portugal' 'Messinia' 'Lakonia'
 'Markopoulo' 'Vinho Licoroso' 'Paardeberg'
 'San Antonio de las Minas Valley' 'Krania Olympus' 'Corinthia'
 'Slovenska Istra' 'Commandaria' 'Gladstone' 'Jerusalem Hills'
 'Mount Athos' 'Colares' 'Helderberg' 'Casablanca & Leyda Valleys'
 'Dealurile Hușilor' 'Urla-Thrace' 'Südburgenland' 'Cape Peninsula'
 'Codru Region' 'Sterea Ellada' 'Muscat of Patras' 'Imathia' 'Alenteo'
 'Canada Other' 'Letrinon' 'Muscat of Kefallonian' 'Thessalikos' 'Hawaii'
 'China' 'Limnos' 'Egypt' 'Viile Timis' 'Devon Valley' 'Krk' 'Arcadia'
 'Cape Agulhas' 'Kathikas' 'Vin de Pays de Velvendo' 'Landwein Rhein'
 'Lesbos' 'Távora-Varosa' 'Neuchâtel']

In [67]:
vinos_buenos_california = data.query("province == 'California' and points > 90")

In [68]:
vinos_buenos_california["variety"].value_counts()

Pinot Noir                        3177
Cabernet Sauvignon                2071
Chardonnay                        1599
Syrah                              769
Zinfandel                          563
                                  ...
Tempranillo-Cabernet Sauvignon       1
Aligoté                              1
Mourvèdre-Syrah                      1
Carignan                             1
Muskat                               1
Name: variety, Length: 126, dtype: int64

# 5. Vinos de Chile evaluados con mas de 90 puntos

In [69]:
vinos_buenos_chile = data.query("country == 'Chile' and points > 90")

In [70]:
vinos_buenos_chile.describe(include="all")

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
count,360.000000,360,360,326,360.000000,359.000000,360,0,0,356,356,360,360,360
unique,NaN,1,341,212,NaN,NaN,29,0,0,2,2,341,26,95
top,NaN,Chile,"This ripe, dark Maipo Syrah opens with slightl...",La Cumbre,NaN,NaN,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Errazuriz 2013 Max Reserva Cabernet Sauvignon ...,Red Blend,Concha y Toro
freq,NaN,360,2,7,NaN,NaN,91,NaN,NaN,355,355,2,124,26
mean,62192.147222,NaN,NaN,NaN,91.683333,58.086351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,37680.494123,NaN,NaN,NaN,0.824249,50.289173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,164.000000,NaN,NaN,NaN,91.000000,13.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,27943.250000,NaN,NaN,NaN,91.000000,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,58609.000000,NaN,NaN,NaN,91.000000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,93626.000000,NaN,NaN,NaN,92.000000,75.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,129259.000000,NaN,NaN,NaN,95.000000,400.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
vinos_buenos_chile

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
164,164,Chile,"This blend of Cabernet Sauvignon, Syrah and Me...",Condesa Real Premium Blend,91,29.0,Aconcagua Valley,NaN,NaN,Michael Schachner,@wineschach,Conde de Velázquez 2012 Condesa Real Premium B...,Red Blend,Conde de Velázquez
165,165,Chile,"Dry, briary aromas of field brush, black olive...",20 Barrels,91,32.0,Maipo Valley,NaN,NaN,Michael Schachner,@wineschach,Cono Sur 2012 20 Barrels Cabernet Sauvignon (M...,Cabernet Sauvignon,Cono Sur
172,172,Chile,"Dry, spicy aromas of tobacco, cedar, vanilla a...",The 7th Generation Gran Reserva Estate Bottled,91,20.0,Loncomilla Valley,NaN,NaN,Michael Schachner,@wineschach,G7 2012 The 7th Generation Gran Reserva Estate...,Cabernet Sauvignon,G7
514,514,Chile,Baked blueberry and boysenberry aromas are mor...,20 Barrels Limited Edition Peralillo Estate,91,35.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Cono Sur 2012 20 Barrels Limited Edition Peral...,Merlot,Cono Sur
530,530,Chile,"Jammy berry aromas seem reduced at first, with...",Cuvée Alexandre Apalta Vineyard Made With Orga...,91,24.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Lapostolle 2013 Cuvée Alexandre Apalta Vineyar...,Syrah,Lapostolle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127453,127453,Chile,"This is concentrated and stout on the nose, wi...",Alpha M,93,100.0,Santa Cruz,NaN,NaN,Michael Schachner,@wineschach,Montes 2009 Alpha M Red (Santa Cruz),Bordeaux-style Red Blend,Montes
128285,128285,Chile,Blackened spice aromas are affixed to blackber...,Gravas del Maipo,92,150.0,Buin,NaN,NaN,Michael Schachner,@wineschach,Concha y Toro 2011 Gravas del Maipo Syrah (Buin),Syrah,Concha y Toro
128628,128628,Chile,"Tight, pure blackberry and cassis aromas are c...",La Finca Clos D'Angel,91,17.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Montes 2013 La Finca Clos D'Angel Cabernet Sau...,Cabernet Sauvignon,Montes
129251,129251,Chile,"Aromas of spice, vanilla and wood are stronger...",Taita,93,300.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Montes 2009 Taita Red (Colchagua Valley),Red Blend,Montes
129259,129259,Chile,"Despite cool conditions in 2011, or quite poss...",Casa Real,93,85.0,Maipo Valley,NaN,NaN,Michael Schachner,@wineschach,Santa Rita 2011 Casa Real Cabernet Sauvignon (...,Cabernet Sauvignon,Santa Rita

# 6. Promedio de puntaje de vino por pais

In [72]:
# En este caso, usamos el group by para agrupar

data.groupby(['country'])["points"].mean()

country
Argentina                 86.710263
Armenia                   87.500000
Australia                 88.580507
Austria                   90.101345
Bosnia and Herzegovina    86.500000
Brazil                    84.673077
Bulgaria                  87.936170
Canada                    89.369650
Chile                     86.493515
China                     89.000000
Croatia                   87.219178
Cyprus                    87.181818
Czech Republic            87.250000
Egypt                     84.000000
England                   91.581081
France                    88.845109
Georgia                   87.686047
Germany                   89.851732
Greece                    87.283262
Hungary                   89.191781
India                     90.222222
Israel                    88.471287
Italy                     88.562231
Lebanon                   87.685714
Luxembourg                88.666667
Macedonia                 86.833333
Mexico                    85.257143
Moldova                   87.203390
Morocco                   88.571429
New Zealand               88.303030
Peru                      83.562500
Portugal                  88.250220
Romania                   86.400000
Serbia                    87.500000
Slovakia                  87.000000
Slovenia                  88.068966
South Africa              88.056388
Spain                     87.288337
Switzerland               88.571429
Turkey                    88.088889
US                        88.563720
Ukraine                   84.071429
Uruguay                   86.752294
Name: points, dtype: float64

# 7. Promedio de puntaje dado por taster

In [73]:
data.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [74]:
data.groupby(['taster_name'])["points"].mean()

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

# 8. Promedio de puntajes por pais de vinos de variedad Pinot Noir

In [75]:
vinos_pinot_noir = data[data["variety"] == "Pinot Noir"]

In [76]:
vinos_pinot_noir

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
21,21,US,"A sleek mix of tart berry, stem and herb, alon...",NaN,87,20.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Acrobat 2013 Pinot Noir (Oregon),Pinot Noir,Acrobat
25,25,US,Oak and earth intermingle around robust aromas...,King Ridge Vineyard,87,69.0,California,Sonoma Coast,Sonoma,Virginie Boone,@vboone,Castello di Amorosa 2011 King Ridge Vineyard P...,Pinot Noir,Castello di Amorosa
35,35,US,As with many of the Erath 2010 vineyard design...,Hyland,86,50.0,Oregon,McMinnville,Willamette Valley,Paul Gregutt,@paulgwine,Erath 2010 Hyland Pinot Noir (McMinnville),Pinot Noir,Erath
41,41,US,"A stiff, tannic wine, this slowly opens and br...",NaN,86,22.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Hawkins Cellars 2009 Pinot Noir (Willamette Va...,Pinot Noir,Hawkins Cellars
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129920,129920,US,"Shows the clean, citrus acid juiciness and sil...",Fiddlestix Vineyard,91,48.0,California,Sta. Rita Hills,Central Coast,NaN,NaN,Pali 2006 Fiddlestix Vineyard Pinot Noir (Sta....,Pinot Noir,Pali
129931,129931,France,"A powerful, chunky wine, packed with solid tan...",NaN,91,107.0,Burgundy,Grands-Echezeaux,NaN,Roger Voss,@vossroger,Henri de Villamont 2005 Grands-Echezeaux,Pinot Noir,Henri de Villamont
129936,129936,France,A blend from several premier cru vineyards in ...,Premier Cru,91,66.0,Burgundy,Pommard,NaN,Roger Voss,@vossroger,Bouchard Père & Fils 2005 Premier Cru (Pommard),Pinot Noir,Bouchard Père & Fils
129960,129960,Portugal,"Fresh and fruity, this is full of red cherry f...",Vértice,90,48.0,Douro,NaN,NaN,Roger Voss,@vossroger,Caves Transmontanas 2006 Vértice Pinot Noir (D...,Pinot Noir,Caves Transmontanas
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation

In [77]:
vinos_pinot_noir.groupby(["country"])["points"].mean()

country
Argentina       85.647619
Australia       87.439394
Austria         90.151515
Brazil          86.000000
Bulgaria        88.533333
Canada          88.521739
Chile           85.917355
Croatia         84.000000
England         91.857143
France          89.754323
Germany         89.436364
Hungary         90.000000
Israel          86.428571
Italy           86.833333
Macedonia       86.000000
New Zealand     88.326130
Portugal        88.368421
Romania         86.200000
Slovenia        88.000000
South Africa    89.033333
Spain           87.000000
Switzerland     89.000000
US              89.607891
Uruguay         85.400000
Name: points, dtype: float64

Si queremos el desagregado de puntaje por tipo de vino y por pais, hacemos:

In [78]:
print(data.groupby(["country", "variety"])["points"].mean())

country    variety
Argentina  Barbera                       85.000000
           Bonarda                       86.504762
           Bordeaux-style Red Blend      89.820225
           Bordeaux-style White Blend    83.000000
           Cabernet Blend                88.250000
                                           ...
Uruguay    Tannat-Cabernet Franc         90.000000
           Tannat-Merlot                 86.500000
           Tannat-Syrah                  84.000000
           Tempranillo-Tannat            88.000000
           White Blend                   87.000000
Name: points, Length: 1612, dtype: float64

In [79]:
# Queda pendiente aprender como expandir estos resultados para revisarlos completamente